config/routes.rb
Rails.application.routes.draw do
  resources :articles, only: [:new, :create, :show, :edit, :update, :index]
  resources :drafts, controller: 'articles', only: [:index], draft: true
  resources :comments, only: [:new, :create, :show, :edit, :update]
  resource :user, only: [:create, :update]
  resource :session, only: [:create]
  match '/code', to: 'pages#code', as: 'code', via: :get
  match '/publications', to: 'pages#publications', as: 'publications', via: :get
  match '/signup', to: 'users#new', as: 'signup', via: :get
  match '/profile', to: 'users#edit', as: 'profile', via: :get
  match '/login', to: 'sessions#new', as: 'login', via: :get
  match '/logout', to: 'sessions#delete', as: 'logout', via: :delete
  match '/robots.txt', to: 'application#robots', via: :get
  match '/sitemap.xml', to: 'application#sitemap', via: :get
  root to: 'articles#index', type: :article
end

app/models/comment.rb
class Comment < ApplicationRecord
  include CommentTree

  has_many :comment_ancestors, foreign_key: :comment_id, class_name: 'Ancestor'
  has_many :ancestors, through: :comment_ancestors, source: :ancestor

  has_many :ancestor_comments, foreign_key: :ancestor_id, class_name: 'Ancestor'
  has_many :successors, through: :ancestor_comments, source: :comment

  belongs_to :user

  belongs_to :parent, foreign_key: 'parent_id', class_name: 'Comment', optional: true
  belongs_to :article

  validates :article, :body, :user, presence: true

  scope :with_user, -> { includes(:user) }
  scope :with_comments, -> { includes(:user, :parent, :article, successors: :user) }

  def comments
    successors
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def show
    @comment = Comment.with_comments.find(params[:id])
    @title = "Comment on '#{@comment.article.title}'"
  end
end

app/views/comments/_comment.html.haml
.comment
  .meta
    = link_to "##{comment.id}", comment_path(comment)
    %span.author= comment.user.display_name
    %span.timestamp{title: comment.updated_at.utc.iso8601}
      = surround '[', ' ago]'do
        = time_ago_in_words comment.updated_at
  .message
    = comment_markdown comment.body
  - unless comment.children.nil?
    .children
      - comment.children.each do |child|
        = render child

app/views/comments/show.html.haml
.root
  = render @comment.article
  %section.comment-body= render @comment