config/routes.rb
Rails.application.routes.draw do
  resources :articles, only: [:new, :create, :show, :edit, :update, :index]
  resources :drafts, controller: 'articles', only: [:index], draft: true
  resources :comments, only: [:new, :create, :show, :edit, :update]
  resource :user, only: [:create, :update]
  resource :session, only: [:create]
  match '/code', to: 'pages#code', as: 'code', via: :get
  match '/publications', to: 'pages#publications', as: 'publications', via: :get
  match '/signup', to: 'users#new', as: 'signup', via: :get
  match '/profile', to: 'users#edit', as: 'profile', via: :get
  match '/login', to: 'sessions#new', as: 'login', via: :get
  match '/logout', to: 'sessions#delete', as: 'logout', via: :delete
  match '/robots.txt', to: 'application#robots', via: :get
  match '/sitemap.xml', to: 'application#sitemap', via: :get
  root to: 'articles#index', type: :article
end

app/models/article.rb
class Article < ApplicationRecord
  include CommentTree

  belongs_to :user

  has_many :comments

  scope :with_user, -> { includes(:user) }
  scope :with_comments, -> { includes(:user, comments: :user) }
  scope :reverse_chron, -> { order(updated_at: :desc) }
  scope :published, -> { where.not(published_at: nil).reverse_chron }
  scope :unpublished, -> { where(published_at: nil).reverse_chron }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
  end

  def create
  end

  def show
    @article = Article.with_comments.find(params[:id])
    @title = @article.title
  end

  def edit
  end

  def index
    @articles = if params[:draft]
      Article.with_user.unpublished
    else
      Article.with_user.published
    end
  end
end

app/views/articles/_article.html.haml
%article.article-summary
  %h1= article.title
  .meta
    By
    %span.author= article.user.display_name
    .timestamp{title: article.updated_at.utc.iso8601}
      = article.updated_at.to_s(:date)
  .body= article_markdown article.tldr
  .link= link_to 'read full article »', article_path(article)

app/views/articles/_tldr.html.haml
%p= article_markdown article.tldr
%p= link_to 'read full article', article_url(article)

app/views/articles/index.html.haml
- @articles.each do |a|
  = render a

app/views/articles/show.html.haml
%h1.title= @article.title
%article.article-body
  .meta
    by
    %span.author= @article.user.display_name
    .timestamp{title: @article.updated_at.utc.iso8601}
      = @article.updated_at.to_s(:date)
  .body= article_markdown @article.body
- unless @article.children.nil?
  %section.comments
    - @article.children.each do |comment|
      = render comment