config/routes.rb
Rails.application.routes.draw do
  resources :articles, only: [:new, :create, :show, :edit, :update, :index]
  resources :drafts, controller: 'articles', only: [:index], draft: true
  resources :comments, only: [:new, :create, :show, :edit, :update]
  resource :user, only: [:create, :update]
  resource :session, only: [:create]
  match '/code', to: 'pages#code', as: 'code', via: :get
  match '/publications', to: 'pages#publications', as: 'publications', via: :get
  match '/signup', to: 'users#new', as: 'signup', via: :get
  match '/profile', to: 'users#edit', as: 'profile', via: :get
  match '/login', to: 'sessions#new', as: 'login', via: :get
  match '/logout', to: 'sessions#delete', as: 'logout', via: :delete
  match '/robots.txt', to: 'application#robots', via: :get
  match '/sitemap.xml', to: 'application#sitemap', via: :get
  root to: 'articles#index', type: :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: true

  def authenticate_user!
    redirect_to login_path unless helpers.logged_in?
  end

  def ensure_logged_out!
    redirect_to root_path if helpers.logged_in?
  end

  def robots
    render plain: (Rails.env.production? ? "" : "User-agent: *\nDisallow: /")
  end

  def sitemap
    headers['Content-Type'] = 'application/xml'
    respond_to do |format|
      format.xml do
        @articles = Article.published
        render layout: false
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def copyright_message
    '© 2005-2019 Srikanth Agaram'
  end
end

app/views/application/sitemap.xml.haml
!!! XML
%urlset{"xmlns" => "http://www.sitemaps.org/schemas/sitemap/0.9", "xmlns:xsi" => "http://www.w3.org/2001/XMLSchema-instance", "xsi:schemaLocation" => "http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd"}
  %url
    %loc= root_url
    %lastmod= @articles.first.updated_at
    %changefreq monthy
  - @articles.each do |article|
    %url
      %loc= article_url(article)
      %lastmod= article.updated_at
      %changefreq monthly
  %url
    %loc= root_url + '/files/srikanth_resume.pdf'
    %lastmod 2019-01-01
    %changefreq monthly
    %priority 0.9
  %url
    %loc= code_url
    %lastmod 2019-01-01
    %changefreq monthly
  %url
    %loc= publications_url
    %lastmod 2019-01-01
    %changefreq monthly