config/routes.rb
Rails.application.routes.draw do
  resources :articles, only: [:new, :create, :show, :edit, :update, :index]
  resources :drafts, controller: 'articles', only: [:index], draft: true
  resources :comments, only: [:new, :create, :show, :edit, :update]
  resource :user, only: [:create, :update]
  resource :session, only: [:create]
  match '/code', to: 'pages#code', as: 'code', via: :get
  match '/publications', to: 'pages#publications', as: 'publications', via: :get
  match '/signup', to: 'users#new', as: 'signup', via: :get
  match '/profile', to: 'users#edit', as: 'profile', via: :get
  match '/login', to: 'sessions#new', as: 'login', via: :get
  match '/logout', to: 'sessions#delete', as: 'logout', via: :delete
  match '/robots.txt', to: 'application#robots', via: :get
  match '/sitemap.xml', to: 'application#sitemap', via: :get
  root to: 'articles#index', type: :article
end

app/views/layouts/_nav.html.haml
#sidebar_button.sidebar-button
%nav.sidebar
  %ul.vertical-list
    %li= link_to 'Home', root_path
    %li= link_to 'Code', code_path
    %li= link_to 'Publications', publications_path
    %li= link_to 'Resume', '/files/srikanth_resume.pdf'
    %li= link_to 'Feed', articles_path(format: :atom)
    - if logged_in?
      %li= link_to 'Log out', logout_path, method: :delete

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      Srikanth Agaram
      - if @title.present?
        = @title
    %meta{name: 'viewport', content: 'width=device-width'}
    = favicon_link_tag 'favicon.png'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true
    = csrf_meta_tag
    = auto_discovery_link_tag(:atom, articles_path(format: :atom))
  %body
    %header#top_header.top-header= render partial: 'layouts/nav'
    %main.content= yield
    %footer.footer= copyright_message